/*
 * generated by Xtext 2.19.0
 */
package com.specmate.objectif.internal.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
        return classLoader.getResourceAsStream("com/specmate/objectif/internal/parser/antlr/internal/InternalDSL.tokens");

		//return classLoader.getResourceAsStream("com/specmate/objectif/parser/antlr/internal/InternalDSL.tokens");
	}
}
