/*
 * generated by Xtext 2.19.0
 */
package com.specmate.objectif.internal.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDSLScopeProvider extends DelegatingScopeProvider {
}
