# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.17.0'
    - name: Start Spacy 
      run: docker run -p "127.0.0.1:80:80" qualicen/spacyapi:en_v2_lg &
    - name: Build Frontend
      run: (cd web && npm run init && npm run build-prod)
    - name: Grant execute permission for gradlew
      run: chmod +x bundles/gradlew
    - name: Build Backend
      run: (cd bundles && ./gradlew --no-daemon jar -x :specmate-dbprovider-oracle:jar)
#    - name: Run Tests
#      run: (cd bundles && ./gradlew --no-daemon check -x :specmate-dbprovider-oracle:check)
    - uses: saucelabs/sauce-connect-action@v1.1.2
      with:
        username: ${{ secrets.SAUCE_USERNAME }}
        accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
        tunnelIdentifier: github-action-tunnel
        scVersion: 4.6.2
    - name: UI-Tests 
      run: |
        (cd bundles && ./gradlew --no-daemon export -x check)
        (export SAUCE_USERNAME=${{ secrets.SAUCE_USERNAME }} && export SAUCE_ACCESS_KEY=${{ secrets.SAUCE_ACCESS_KEY }} && cd bundles/specmate-std-env/generated/distributions/executable/ && java -Xmx6000m -Djdk.crypto.KeyAgreement.legacyKDF=true -jar dev-specmate-all.jar &)    
        sleep 10    
        (cd ui-tests/ && mvn clean test)
